language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=26.0.2
android:
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
before_script:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
script:
- "./gradlew build check"
before_install:
- openssl aes-256-cbc -K $encrypted_a2f4f56a107e_key -iv $encrypted_a2f4f56a107e_iv
  -in keystore.jks.enc -out keystore.jks -d
deploy:
  provider: releases
  api_key:
    secure: Q2SFYDhxLoUCO1wCu5V6T4OCkhFguHxpnN1KMu8UhT0y4nIDplMnfRiCZOu1y6798yNdvY9KXD3f4q6stHm/29Ion/9HcCYlurwC+VNvkzVNwstqi5I1iHTy8vnKgOqpyLaeuAYqraKHFDvlLecVB236l9xt0pA09RVDm5i2RzCW0Ul5+YGiUCO4YqwiDduBINLTWhRvDo5glQtQcUb+QvQ7z3mi5Y0KFG3CK08GcEV9+l3eFjaBo3CCb5eyHIw8QX173r3DHfx2H+rUB6Ajjf7mh8ZMb4kVIE1bXLQibFCnEAITpjVirTy861+QDtE8u74bwJtA1TE4LMqxXZJC6He2EQ6i4rqaXQdaFnuxXYyWmmM6Y75wxUvVPn4UMnJzxxauBXHiP9igXf0SoQvT3UUAENE/vd6MNIfMOInNzXknp7pztHzV/Wz+eKHruhWJqjgJo1lIw9htFz1PczmQnwo+MOkTW4Jll9Cp32pomNKcqh9pSfmB+a6Cpde24oylu2jtHw1pIcgX29hSWCbGMo5ZpD1j89zM1TISMTDe/VhP++SVahGuQyGCsHPPtvAgX/ktg2wmgrR1uoGtalO6XUgLuYA9NxYo6p1nNw2colcOaJbw28wMQvc1X2z77t8H2k779uqGzpYZU3yyVsRj8eN6CvOGjJpkl1VGQyO8eJo=
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    repo: hoangth12495/TravisCIdemo
    tags: true
